name: "E-Commerce App continuous Integration"

on: [ push ]

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo.
        uses: actions/checkout@v2
      - name: Install dependencies.
        run: composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader
      - name: Build containers.
        run: docker-compose up -d --build --force-recreate
      - name: Wait for sometime[30 sec] until containers are ready.
        run: sleep 30
      - name: Run unit tests.
        run: docker container exec ecommerce-app-app /ecommerce-app/phpunit tests/
