name: "E-Commerce App continuous Integration"

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker-compose --version
        name: "Docker compose installation test"
